name: Build ISO
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            grub-pc-bin grub-efi-amd64-bin xorriso grub-common mtools \
            golang gcc g++ \
            libcurl4-dev libssl-dev libarchive-dev libzstd-dev \
            zlib1g-dev libbz2-dev

      - name: Build components
        run: |
          bash build-and-launch.sh --fetch <<< "y"

      - name: Build ISO
        run: |
          bash make-iso.sh <<< "y"

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: galactica-installer-iso
          path: galactica-installer.iso
          retention-days: 7