name: Release Base Config

on:
  push:
    tags:
      - 'base-config-*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        default: '1.0.0'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package
        run: bash pkg.sh --config-only

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: base-config-${{ inputs.version }}
          name: Base Config ${{ inputs.version }}
          files: galactica-packages/tarballs/base-config-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
